import type { Metadata } from "next";
import "./globals.css";
import "@fontsource-variable/montserrat";
import FloatingControls from "@/components/FloatingControls";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="https://fonts.cdnfonts.com/css/minecraft-4" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var t = localStorage.getItem('bb-theme');
                  if (!t) {
                    t = (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light';
                  }
                  if (t === 'light') {
                    document.documentElement.classList.add('theme-light');
                  } else {
                    document.documentElement.classList.remove('theme-light');
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body className={`antialiased`}>
        <FloatingControls />
        {children}
      </body>
    </html>
  );
}
